name:                elephantom
version:             0.1.0.0
github:              "ukari/elephantom"
license:             BSD3
author:              "chendianbuji"
maintainer:          "chendianbuji@gmail.com"
copyright:           "2020 chendianbuji@gmail.com"

extra-source-files:
- README.md
- ChangeLog.md

c-sources:
- src/*.c

## only used for dev
data-dir: "assets"
data-files:
- font/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ukari/elephantom#readme>

dependencies:
- base >= 4.7 && < 5
- Cabal
- gitrev
- hspec

library:
  source-dirs: src
  dependencies:
  - word24
  - lens
  - relude
  - template-haskell
  - kazura-queue
  - streamly
  - conduit
  - conduit-extra
  - scheduler
  - reflex
  - time
  - dependent-sum
  - microlens-platform
  - containers
  - linear >= 1.21.5
  - vector >= 0.12.3.0
  - vector-algorithms
  - text
  - binary
  - bytestring
  - utf8-string
  - qm-interpolated-string
  - filepath
  - directory
  - typed-process
  - temporary-rc
  - aeson
  - recursion-schemes
  - attoparsec
  - parsec
  - StateVar
  - sdl2
  - vulkan
  - vulkan-utils
  - VulkanMemoryAllocator
  - resourcet
  - lifetimes
  - unliftio-core
  - ad
  - random
  - massiv >= 0.6.1.0
  - massiv-io >= 0.4.1.0
  - JuicyPixels
  - FontyFruity
  - Rasterific
  - fused-effects
  - fused-effects-exceptions
  - transformers
  - monad-logger
  - derive-storable

executables:
  elephantom:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    ## for stan analysis
    #- -fwrite-ide-info
    #- -hiedir=.hie
    - -fplugin=Foreign.Storable.Generic.Plugin
    - -fplugin-opt=Foreign.Storable.Generic.Plugin:-v1
    ## debug
    #- -W
    #- -fprint-potential-instances
    dependencies:
    - elephantom
    - derive-storable-plugin

tests:
  elephantom-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elephantom
