name:                elephantom
version:             0.1.0.0
github:              "ukari/elephantom"
license:             BSD3
author:              "chendianbuji"
maintainer:          "chendianbuji@gmail.com"
copyright:           "2020 chendianbuji@gmail.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ukari/elephantom#readme>

dependencies:
- base >= 4.7 && < 5
- Cabal
- gitrev
- hspec

library:
  source-dirs: src
  dependencies:
  - template-haskell
  - streamly
  - containers
  - linear
  - vector
  - vector-algorithms
  - text
  - bytestring
  - qm-interpolated-string
  - recursion-schemes
  - parsec
  - sdl2
  - vulkan
  - vulkan-utils
  - VulkanMemoryAllocator
  - resourcet
  - repa
  - JuicyPixels-repa
  - JuicyPixels
  - Rasterific
  - errors
  - fused-effects
  - transformers
  - derive-storable
  - offset

executables:
  elephantom:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    ## for stan analysis
    #- -fwrite-ide-info
    #- -hiedir=.hie
    - -fplugin=Foreign.Storable.Generic.Plugin
    - -fplugin-opt=Foreign.Storable.Generic.Plugin:-v1
    ## debug
    #- -W
    #- -fprint-potential-instances
    dependencies:
    - elephantom
    - derive-storable-plugin

tests:
  elephantom-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elephantom
